Repository GoogleCloudPlatform/cloud-ops-sandbox, pull requests merged in 2020-08, with the labels that each got.

#235 Update Cloud Shell Button URL
  docs/index.html
Labels: cla: yes

#246 restore ochttp metrics for userexp dashboard
  src/frontend/main.go
Labels: cla: yes, lang: go, priority: p1, type: bug

#247 Label CI workers
  .github/workflows/README.md
  .github/workflows/ci.yml
Labels: cla: yes, priority: p2, type: process

#250 Use custom cloudshell image
  docs/index.html
Labels: cla: yes

#240 add monitoring as part of installation
  terraform/install.sh
Labels: cla: yes, lang: shell, priority: p1, type: bug

#254 Integrate Cloud Shell in release process
  .github/workflows/push-tags.yml
  make-release.sh
Labels: cla: yes, lang: yaml, priority: p1, type: process

#253 Updated documentation for custom image
  docs/README.md
  docs/images/user-guide/TrustImage.png
Labels: cla: yes, lang: shell, priority: p1, type: process

#245 Add owner permission check and credential check
  terraform/00_state.tf
  terraform/02_project.tf
  terraform/03_gke_cluster.tf
  terraform/destroy.sh
  terraform/install.sh
  terraform/variables.tf
Labels: cla: yes, lang: shell, priority: p1, type: process

#259 add project to monitoring terraform provider
  terraform/monitoring/00_provider.tf
  terraform/monitoring/02_dashboards.tf
  terraform/monitoring/variables.tf
Labels: cla: yes, lang: yaml, priority: p1, type: bug

#265 fix email and deprecations
  terraform/03_gke_cluster.tf
  terraform/install.sh
  terraform/monitoring/02_dashboards.tf
Labels: cla: yes, priority: p1, type: bug

#270 fix interpolation
  terraform/monitoring/00_provider.tf
Labels: cla: yes, priority: p1, type: bug

#269 Fix Googler authentication
  terraform/install.sh
Labels: cla: yes

#271 set current project
  terraform/install.sh
Labels: cla: yes, priority: p1, type: bug

#273 gcloud auth
  terraform/install.sh
Labels: cla: yes, priority: p1, type: bug

#274 Release/v0.2.0
  docs/index.html
Labels: cla: yes

#282 get rid of interpolations for terraform
  terraform/monitoring/00_provider.tf
  terraform/monitoring/02_dashboards.tf
Labels: cla: yes, lang: yaml, priority: p2, type: bug

#283 Adding CODEOWNERS
  CODEOWNERS
Labels: cla: yes, priority: p2, type: process

#277 OpenTelemetry Tracing for Checkout Service + Reuse gRPC Connections
  src/checkoutservice/Dockerfile
  src/checkoutservice/Gopkg.lock
  src/checkoutservice/Gopkg.toml
  src/checkoutservice/main.go
Labels: cla: yes, lang: go, priority: p2, type: process

#239 Allow install.sh to be driven by the command line
  terraform/install.sh
Labels: cla: yes, priority: p2, type: process

#288 Improve tag actions
  .github/workflows/push-tags.yml
Labels: cla: yes, lang: yaml, type: process

#280 Migrating website to AppEngine
  .github/workflows/push-tags.yml
  app.yaml
  docs/user-guide/1-architecture.png
  docs/user-guide/10-tracereport.png
  docs/user-guide/11-profiler.png
  docs/user-guide/12-profilerservice.png
  docs/user-guide/13-profilermetric.png
  docs/user-guide/14-debugger.png
  docs/user-guide/15-codeupload.png
  docs/user-guide/16-selectsource.png
  docs/user-guide/17-snapshot.png
  docs/user-guide/18-logpoint.png
  docs/user-guide/19-gcp-monitoring-overview.png
  docs/user-guide/2-hipstershop.png
  docs/user-guide/20-monitoring-dashboards-kubernetes.png
  docs/user-guide/21-metrics-explorer.png
  docs/user-guide/22-lbms.png
  docs/user-guide/23-logs.png
  docs/user-guide/24-metriceditor.png
  docs/user-guide/25-explorer.png
  docs/user-guide/26-logging.png
  docs/user-guide/27-logs.png
  docs/user-guide/28-morelogs.png
  docs/user-guide/29-exporting-logs.png
  docs/user-guide/3-locust.png
  docs/user-guide/30-bucket.png
  docs/user-guide/31-errorrep.png
  docs/user-guide/32-errordet.png
  docs/user-guide/33-samples.png
  docs/user-guide/34-logs.png
  docs/user-guide/35-logdet.png
  docs/user-guide/4-cloudconsole.png
  docs/user-guide/5-operations-products.png
  docs/user-guide/6-trace.png
  docs/user-guide/7-tracelist.png
  docs/user-guide/8-tracedetail.png
  docs/user-guide/9-traceanalysis.png
  docs/user-guide/TrustImage.png
  website/CNAME
  website/README.md
  website/cloudbuild.yaml
  website/css/main.css
  website/images/bg_01.png
  website/images/bg_02.png
  website/images/cloud-logo.svg
  website/images/cloud-shell.svg
  website/images/cloud.svg
  website/images/content_copy.svg
  website/images/done.svg
  website/images/github.svg
  website/images/google-cloud-logotype.svg
  website/images/hex_bg.svg
  website/images/logo_stackdriver.svg
  website/index.html
Labels: cla: yes, lang: shell, priority: p2, type: feature request

#289 Added logic to push-master.yml to create cloud image
  .github/workflows/push-master.yml
Labels: cla: yes, lang: yaml, priority: p2, type: process

#303 Rollback changes: add website files back to docs folder
  docs/CNAME
  docs/css/main.css
  docs/images/bg_01.png
  docs/images/bg_02.png
  docs/images/cloud-logo.svg
  docs/images/cloud-shell.svg
  docs/images/cloud.svg
  docs/images/content_copy.svg
  docs/images/done.svg
  docs/images/github.svg
  docs/images/google-cloud-logotype.svg
  docs/images/hex_bg.svg
  docs/images/logo_stackdriver.svg
  docs/index.html
Labels: cla: yes

#292 OpenTelemetry Tracing for Recommendation Service
  src/recommendationservice/Dockerfile
  src/recommendationservice/client.py
  src/recommendationservice/recommendation_server.py
  src/recommendationservice/requirements.in
  src/recommendationservice/requirements.txt
Labels: cla: yes, lang: python, priority: p2, type: process

#162 OpenTelemetry Tracing for Email Service
  src/emailservice/email_server.py
  src/emailservice/requirements.in
  src/emailservice/requirements.txt
Labels: cla: yes, lang: python, priority: p2, type: process

#305 Fix GitHub Actions Issues
  .github/workflows/push-master.yml
  .github/workflows/push-tags.yml
Labels: cla: yes, lang: yaml, priority: p2, type: process

#301 emphasize workspace creation in install.sh
  terraform/install.sh
Labels: cla: yes, lang: shell, priority: p2, type: process

#314 Fix GitHub Action Push Bug
  .github/workflows/push-master.yml
Labels: cla: yes, lang: yaml, priority: p2, type: process

#313 Added test to CI to Build Custom Cloud Shell Image
  .github/workflows/ci.yml
Labels: cla: yes, lang: yaml, priority: p2, type: process

#315 fix project_id in terraform
  terraform/02_project.tf
  terraform/03_gke_cluster.tf
Labels: cla: yes, lang: yaml, priority: p2, type: bug

#320 Revert GCP dependencies updates that cause auth problems
  src/currencyservice/package-lock.json
  src/currencyservice/package.json
  src/emailservice/requirements.txt
  src/paymentservice/package-lock.json
  src/paymentservice/package.json
  src/recommendationservice/requirements.txt
Labels: cla: yes, dependencies, priority: p2

#304 End-to-End CI test
  .github/workflows/README.md
  .github/workflows/e2e.yml
  .github/workflows/e2e_scripts/clean.sh
  .github/workflows/e2e_scripts/run_install.sh
  terraform/02_project.tf
  terraform/install.sh
  terraform/variables.tf
Labels: cla: yes, lang: shell, priority: p2, type: process

#330 Moved user guide images to former directory
  docs/images/user-guide/1-architecture.png
  docs/images/user-guide/10-tracereport.png
  docs/images/user-guide/11-profiler.png
  docs/images/user-guide/12-profilerservice.png
  docs/images/user-guide/13-profilermetric.png
  docs/images/user-guide/14-debugger.png
  docs/images/user-guide/15-codeupload.png
  docs/images/user-guide/16-selectsource.png
  docs/images/user-guide/17-snapshot.png
  docs/images/user-guide/18-logpoint.png
  docs/images/user-guide/19-gcp-monitoring-overview.png
  docs/images/user-guide/2-hipstershop.png
  docs/images/user-guide/20-monitoring-dashboards-kubernetes.png
  docs/images/user-guide/21-metrics-explorer.png
  docs/images/user-guide/22-lbms.png
  docs/images/user-guide/23-logs.png
  docs/images/user-guide/24-metriceditor.png
  docs/images/user-guide/25-explorer.png
  docs/images/user-guide/26-logging.png
  docs/images/user-guide/27-logs.png
  docs/images/user-guide/28-morelogs.png
  docs/images/user-guide/29-exporting-logs.png
  docs/images/user-guide/3-locust.png
  docs/images/user-guide/30-bucket.png
  docs/images/user-guide/31-errorrep.png
  docs/images/user-guide/32-errordet.png
  docs/images/user-guide/33-samples.png
  docs/images/user-guide/34-logs.png
  docs/images/user-guide/35-logdet.png
  docs/images/user-guide/4-cloudconsole.png
  docs/images/user-guide/5-operations-products.png
  docs/images/user-guide/6-trace.png
  docs/images/user-guide/7-tracelist.png
  docs/images/user-guide/8-tracedetail.png
  docs/images/user-guide/9-traceanalysis.png
  docs/images/user-guide/TrustImage.png
Labels: cla: yes, lang: markdown, priority: p2, type: bug

#331 enable sourcerepo api
  terraform/02_project.tf
Labels: cla: yes, priority: p2, type: bug

#336 Add OpenTelemetry Tracing for Payment service
  src/paymentservice/index.js
  src/paymentservice/package-lock.json
  src/paymentservice/package.json
  src/paymentservice/server.js
  src/paymentservice/tracer.js
Labels: cla: yes, lang: nodejs, priority: p2

#312 OpenTelemetry Tracing for Currency Service
  src/checkoutservice/main.go
  src/currencyservice/package-lock.json
  src/currencyservice/package.json
  src/currencyservice/server.js
Labels: cla: yes, lang: nodejs, priority: p2, type: bug

#338 Documentation for OpenTelemetry Instrumentation
  src/checkoutservice/main.go
  src/currencyservice/server.js
  src/emailservice/email_server.py
  src/frontend/main.go
  src/paymentservice/tracer.js
  src/productcatalogservice/server.go
  src/recommendationservice/recommendation_server.py
  src/shippingservice/main.go
Labels: api: docs, cla: yes, priority: p3

#337 sandbox rebranding
  terraform/02_project.tf
  terraform/03_gke_cluster.tf
  terraform/destroy.sh
  terraform/install.sh
Labels: cla: yes, priority: p2, type: feature request

#342 fixed cluster name in e2e test
  .github/workflows/e2e_scripts/clean.sh
Labels: cla: yes, lang: yaml, priority: p2, type: bug

#335 Monitoring Integration Test added to E2E CI
  .github/workflows/e2e.yml
  .github/workflows/e2e_scripts/clean.sh
  .github/workflows/e2e_scripts/cleanup_monitoring.py
  .github/workflows/e2e_scripts/requirements.txt
  .github/workflows/install-dependencies.sh
  tests/monitoring_integration_test.py
Labels: cla: yes, lang: python, lang: yaml, priority: p2, type: feature request

#316 SLO and Alerting Policies for Custom Services
  terraform/monitoring/03_services.tf
  terraform/monitoring/04_alerting_policies.tf
  terraform/monitoring/04_slos.tf
  terraform/monitoring/05_alerting_policies.tf
  tests/monitoring_integration_test.py
Labels: cla: yes, lang: python, lang: yaml, priority: p2, type: feature request

#344 Updated root documentation
  README.md
Labels: cla: yes, lang: markdown, priority: p2, type: docs

#322 istio service SLO and alerting policies
  terraform/install.sh
  terraform/monitoring/03_services.tf
  terraform/monitoring/04_slos.tf
  terraform/monitoring/05_alerting_policies.tf
  terraform/monitoring/variables.tf
  tests/monitoring_integration_test.py
Labels: cla: yes, lang: python, lang: yaml, priority: p2, type: feature request

#351 Update clustername for development
  Makefile
Labels: cla: yes, lang: shell, priority: p2

#353 added google api client to packages for integration tests
  tests/requirements.txt
Labels: cla: yes, priority: p2, type: process

#281 Custom Dashboards for Remaining Services
  terraform/monitoring/02_dashboards.tf
  terraform/monitoring/dashboards/cartservice_dashboard.json
  terraform/monitoring/dashboards/checkoutservice_dashboard.json
  terraform/monitoring/dashboards/currencyservice_dashboard.json
  terraform/monitoring/dashboards/productcatalogservice_dashboard.json
  tests/monitoring_integration_test.py
Labels: cla: yes, lang: yaml, priority: p2, type: feature request

#302 Add integration test for Sandbox provisioning
  .github/workflows/e2e.yml
  tests/provisioning/Dockerfile
  tests/provisioning/README.md
  tests/provisioning/provision_test.py
  tests/provisioning/requirements.txt
Labels: cla: yes, lang: python, priority: p2, type: process

#345 Log based metric for checkout service
  .github/workflows/e2e_scripts/cleanup_monitoring.py
  src/checkoutservice/main.go
  terraform/monitoring/06_log_based_metric.tf
  tests/monitoring_integration_test.py
Labels: cla: yes, lang: python, lang: yaml, priority: p2, type: feature request

#373 Find old projects in destroy.sh
  terraform/destroy.sh
Labels: cla: yes, priority: p1, type: feature request

#368 Increase Googler auth timeout
  terraform/install.sh
Labels: cla: yes, priority: p1, type: feature request

#379 Debranding stackdriver from user guide
  docs/README.md
Labels: cla: yes, priority: p1, type: process

#382 Release updates readme
  README.md
  docs/index.html
  make-release.sh
Labels: cla: yes, priority: p1, type: process

#385 [docs] update image for debugger
  docs/images/user-guide/15-codeupload.png
Labels: cla: yes, priority: p3, type: docs

#384 Local test
  tests/provisioning/README.md
Labels: cla: yes, priority: p2, type: bug

#352 Cloudbuild file change
  .github/workflows/README.md
  .github/workflows/update-custom-image.yml
  cloud-shell/cloudbuild.yaml
Labels: cla: yes, lang: yaml, priority: p2, type: process

#361 reorder e2e cleanup to clean monitoring first
  .github/workflows/e2e.yml
  .github/workflows/e2e_scripts/clean.sh
  .github/workflows/e2e_scripts/cleanup_monitoring.py
  loadgenerator/loadgen
  terraform/install.sh
  terraform/monitoring/05_alerting_policies.tf
  terraform/monitoring/istio_service_setup.py
  tests/monitoring_integration_test.py
Labels: cla: yes, priority: p2, type: bug

#390 bug fix for indefinite service wait
  terraform/install.sh
  terraform/monitoring/istio_service_setup.py
Labels: cla: yes, priority: p2, type: bug

#387 remove existing load generator when using old projects
  terraform/install.sh
Labels: cla: yes, priority: p2, type: bug

#391 Push tagged image
  cloud-shell/cloudbuild.yaml
Labels: cla: yes, lang: yaml, priority: p1, type: bug

#393 Release/v0.2.5
  README.md
  docs/index.html
  make-release.sh
Labels: cla: yes, priority: p1, type: process

#401 Update terraform version
  cloud-shell/Dockerfile
Labels: cla: yes, lang: shell, priority: p2, type: process

#406 End-to-end release test
  .github/workflows/README.md
  .github/workflows/e2e-latest.yml
  .github/workflows/e2e-release.yml
  .github/workflows/e2e_scripts/run_install.sh
Labels: cla: yes, lang: shell, type: feature request

#402 Fix Cloud Shell GitHub Actions
  .github/workflows/README.md
  .github/workflows/push-master.yml
  .github/workflows/push-tags.yml
  .github/workflows/update-custom-image.yml
  cloud-shell/cloudbuild.yaml
Labels: cla: yes

#410 Replace smoke test
  .github/workflows/ci.yml
Labels: cla: yes, lang: yaml, priority: p2

#413 Create googlers sandboxes in a new folder
  terraform/install.sh
Labels: cla: yes, lang: yaml, priority: p2, type: process
