Repository GoogleCloudPlatform/cloud-ops-sandbox, pull requests merged in 2020-11, with the labels that each got.

#555 fix: e2e release tests
  .github/workflows/e2e-release.yml
Labels: automerge, cla: yes, lang: yaml, priority: p2, type: bug

#557 fix: e2e release tests
  .github/workflows/e2e-release.yml
Labels: cla: yes, lang: yaml

#556 chore: add blunderbuss
  .github/blunderbuss.yml
Labels: cla: yes, lang: yaml, priority: p2

#563 fixed parameter name
  terraform/monitoring/istio_service_setup.py
Labels: cla: yes, lang: python

#554 integrate rating service into deployment pipeline
  README.md
  cloud-shell/Dockerfile
  src/ratingservice/.gcloudignore
  src/ratingservice/README.md
  src/ratingservice/app.template
  src/ratingservice/main.py
  terraform/02_project.tf
  terraform/03_ratingservice.tf
  terraform/README.md
  terraform/monitoring/istio_service_setup.py
  terraform/ratingservice/configure_rating_db.sh
  terraform/ratingservice/deploy_rating_service.sh
  terraform/serverless/04_cloudsql.tf
  terraform/serverless/05_app_engine.tf
  terraform/serverless/info.tf
  terraform/serverless/install_serverless.sh
  terraform/variables.tf
  tests/ratingservice/main_test.py
Labels: cla: yes, lang: manifest, priority: p2, type: feature request

#567 Warn clicking will terminate Cloud Shell sessions
  website/css/main.css
  website/index.html
Labels: cla: yes, lang: css

#565 Implement a mocked UI for product rating
  src/frontend/static/css/styles.css
  src/frontend/templates/footer.html
  src/frontend/templates/header.html
  src/frontend/templates/home.html
  src/frontend/templates/product.html
Labels: cla: yes, lang: go, priority: p2, type: feature request

#570 Put manual workspace creation near start of script
  terraform/install.sh
Labels: cla: yes, lang: shell, priority: p2, type: feature request

#568 Warn clicking will terminate Cloud Shell sessions (part 2)
  website/index.html
Labels: cla: yes, lang: css

#577 Implement tech debt and fix #576
  .github/workflows/e2e-latest.yml
  terraform/ratingservice/configure_rating_db.sh
  terraform/ratingservice/main.tf
  terraform/ratingservice/setup_app_engine.sh
  tests/ratingservice/main_test.py
Labels: cla: yes, lang: manifest
