Repository GoogleCloudPlatform/cloud-ops-sandbox, pull requests merged in 2020-07, with the labels that each got.

#83 Add GitHub Actions CI
  .github/workflows/README.md
  .github/workflows/ci.yml
  .github/workflows/install-dependences.sh
  .travis.yml
  docs/css/main.css
  docs/index.html
  docs/scripts/metrics.js
  kubernetes-manifests/adservice.yaml
  kubernetes-manifests/cartservice.yaml
  kubernetes-manifests/checkoutservice.yaml
  kubernetes-manifests/currencyservice.yaml
  kubernetes-manifests/emailservice.yaml
  kubernetes-manifests/frontend.yaml
  kubernetes-manifests/paymentservice.yaml
  kubernetes-manifests/productcatalogservice.yaml
  kubernetes-manifests/recommendationservice.yaml
  kubernetes-manifests/redis.yaml
  kubernetes-manifests/shippingservice.yaml
  pb/demo.proto
  src/adservice/Dockerfile
  src/adservice/src/main/proto/demo.proto
  src/adservice/src/main/resources/log4j2.xml
  src/cartservice/Dockerfile
  src/checkoutservice/Dockerfile
  src/checkoutservice/genproto/demo.pb.go
  src/currencyservice/Dockerfile
  src/currencyservice/proto/demo.proto
  src/emailservice/Dockerfile
  src/emailservice/email_server.py
  src/emailservice/logger.py
  src/emailservice/requirements.in
  src/emailservice/requirements.txt
  src/emailservice/templates/confirmation.html
  src/frontend/Dockerfile
  src/frontend/genproto/demo.pb.go
  src/frontend/templates/ad.html
  src/frontend/templates/cart.html
  src/frontend/templates/error.html
  src/frontend/templates/footer.html
  src/frontend/templates/header.html
  src/frontend/templates/home.html
  src/frontend/templates/order.html
  src/frontend/templates/product.html
  src/frontend/templates/recommendations.html
  src/loadgenerator/Dockerfile
  src/paymentservice/Dockerfile
  src/paymentservice/package.json
  src/paymentservice/proto/demo.proto
  src/productcatalogservice/Dockerfile
  src/productcatalogservice/genproto/demo.pb.go
  src/recommendationservice/Dockerfile
  src/shippingservice/Dockerfile
  src/shippingservice/genproto/demo.pb.go
  terraform/variables.tf
Labels: enhancement

#141 Update README.md
  README.md
Labels: cla: yes, lang: shell, type: docs

#126 [refactor] Rename loadgenerator-tool to loadgen
  CONTRIBUTING.md
  loadgenerator/loadgen
  terraform/install.sh
Labels: cla: yes, lang: python, type: feature request

#135 Remove opencensus jaeger exporter
  kubernetes-manifests/adservice.yaml
  kubernetes-manifests/checkoutservice.yaml
  kubernetes-manifests/frontend.yaml
  kubernetes-manifests/productcatalogservice.yaml
  kubernetes-manifests/shippingservice.yaml
  src/adservice/build.gradle
  src/adservice/src/main/java/hipstershop/AdService.java
  src/checkoutservice/Gopkg.lock
  src/checkoutservice/main.go
  src/frontend/Gopkg.lock
  src/frontend/main.go
  src/productcatalogservice/server.go
  src/shippingservice/Gopkg.lock
  src/shippingservice/main.go
Labels: cla: yes, lang: go, type: cleanup

#122 User experience dashboard
  terraform/monitoring/00_provider.tf
  terraform/monitoring/02_dashboards.tf
Labels: cla: yes, lang: yaml, type: feature request

#151 Add scopes to cluster
  CONTRIBUTING.md
  Makefile
Labels: cla: yes

#112 HTTP Uptime Check and Alerting Policy
  CONTRIBUTING.md
  terraform/README.md
  terraform/monitoring/00_provider.tf
  terraform/monitoring/01_uptime_checks.tf
  terraform/monitoring/README.md
  terraform/monitoring/variables.tf
Labels: cla: yes, lang: yaml

#160 Added documentation of destroy.sh
  docs/README.md
Labels: cla: yes, type: docs

#158 Remove travis ci, update renovate bot settings
  .travis.yml
  README.md
  renovate.json
  skaffold.yaml
Labels: automerge, cla: yes, dependencies, lang: yaml

#164 docs: instructions for building and running using docker locally
  CONTRIBUTING.md
Labels: cla: yes, priority: p3, type: docs

#165 Remove metrics for next19 conf from sandbox landing page
  docs/index.html
  docs/scripts/metrics.js
Labels: cla: yes, priority: p2, type: bug, type: process

#166 Added integration tests for monitoring examples
  tests/README.md
  tests/monitoring_integration_test.py
  tests/requirements.txt
Labels: cla: yes, lang: python, priority: p2, type: feature request

#167 Refactor: remove customize script
  kubernetes-manifests/adservice.yaml
  kubernetes-manifests/cartservice.yaml
  kubernetes-manifests/checkoutservice.yaml
  kubernetes-manifests/currencyservice.yaml
  kubernetes-manifests/emailservice.yaml
  kubernetes-manifests/frontend.yaml
  kubernetes-manifests/paymentservice.yaml
  kubernetes-manifests/productcatalogservice.yaml
  kubernetes-manifests/recommendationservice.yaml
  kubernetes-manifests/shippingservice.yaml
  skaffold.yaml
  terraform/03_gke_cluster.tf
  terraform/customize-manifests.sh
Labels: cla: yes, lang: yaml, type: cleanup

#169 Release/v0.1.14
  docs/index.html
Labels: cla: yes

#139 Install Istio 1.6.2 for Stackdriver Sandbox
  CONTRIBUTING.md
  Makefile
  istio-manifests/frontend-gateway.yaml
  istio-manifests/frontend.yaml
  istio-manifests/istio-manifests.yaml
  terraform/03_gke_cluster.tf
  terraform/install.sh
  terraform/istio/install_istio.sh
  terraform/istio/istio_operator.yaml
Labels: cla: yes, lang: shell, lang: yaml, priority: p2, type: feature request

#170 Fixing intermittent auth issues in CI
  .github/workflows/README.md
  .github/workflows/ci.yml
  .github/workflows/install-dependencies.sh
  docs/index.html
  skaffold.yaml
Labels: cla: yes

#172 Push images on commits and tags
  .github/workflows/README.md
  .github/workflows/push-master.yml
  .github/workflows/push-tags.yml
Labels: cla: yes

#173 upgrade terraform version
  terraform/install.sh
Labels: cla: yes, lang: shell, priority: p2, type: feature request

#174 Added new release script
  RELEASING.md
  cloudbuild-release.yaml
  make-release.sh
Labels: cla: yes

#177 Fix python dependencies
  src/emailservice/email_server.py
  src/emailservice/requirements.in
  src/emailservice/requirements.txt
  src/recommendationservice/Dockerfile
  src/recommendationservice/recommendation_server.py
  src/recommendationservice/requirements.in
  src/recommendationservice/requirements.txt
Labels: cla: yes, dependencies, lang: python

#179 Fix java dependencies
  src/adservice/Dockerfile
  src/adservice/README.md
  src/adservice/build.gradle
  src/adservice/gradle/wrapper/gradle-wrapper.jar
  src/adservice/gradle/wrapper/gradle-wrapper.properties
  src/adservice/gradlew
  src/adservice/gradlew.bat
  src/adservice/src/main/java/hipstershop/AdServiceClient.java
Labels: cla: yes

#180 Update Python OpenCensus
  src/emailservice/email_server.py
  src/emailservice/requirements.in
  src/emailservice/requirements.txt
  src/recommendationservice/recommendation_server.py
  src/recommendationservice/requirements.in
  src/recommendationservice/requirements.txt
Labels: cla: yes, dependencies, lang: python

#182 Updating package dependencies in cart service
  src/cartservice/Dockerfile
  src/cartservice/cartservice.csproj
  tests/cartservice/cartservice.tests.csproj
Labels: cla: yes, dependencies, lang: dotnet

#175 frontend dashboards
  terraform/monitoring/02_dashboards.tf
  terraform/monitoring/dashboards/frontend_dashboard.json
  terraform/monitoring/dashboards/userexp_dashboard.json
  terraform/monitoring/variables.tf
  tests/monitoring_integration_test.py
Labels: cla: yes, lang: yaml, priority: p2, type: feature request

#176 adservice and recommendationservice custom dashboards
  terraform/monitoring/02_dashboards.tf
  terraform/monitoring/dashboards/adservice_dashboard.json
  terraform/monitoring/dashboards/recommendationservice_dashboard.json
  tests/monitoring_integration_test.py
Labels: cla: yes, lang: yaml, priority: p2, type: feature request

#199 generic service dashboards (emailservice, paymentservice, shippingservice)
  terraform/monitoring/02_dashboards.tf
  terraform/monitoring/dashboards/generic_dashboard.tmpl
  tests/monitoring_integration_test.py
Labels: cla: yes, lang: python, lang: yaml, priority: p2, type: feature request

#183 Telemetry frontend: metrics to stdout, tracing in http handlers, gRPC interceptor
  src/frontend/Dockerfile
  src/frontend/Gopkg.lock
  src/frontend/Gopkg.toml
  src/frontend/main.go
  src/frontend/middleware.go
Labels: cla: yes, dependencies, lang: go, priority: p2

#214 Changed node type to n1-standard-2
  terraform/03_gke_cluster.tf
Labels: cla: yes, lang: shell, priority: p2

#185 Custom image to run ./install.sh
  cloud-shell/Dockerfile
  cloud-shell/README.md
  cloud-shell/cloudbuild.yaml
  cloud-shell/cloudshell_open_cp.sh
  docs/index.html
Labels: cla: yes, lang: shell, priority: p2, type: process

#186 Adding google.com accounts support and terraform stateful provisioning
  terraform/00_state.tf
  terraform/02_project.tf
  terraform/03_gke_cluster.tf
  terraform/destroy.sh
  terraform/install.sh
  terraform/variables.tf
Labels: cla: yes, lang: shell, lang: yaml, type: feature request

#184 frontend SLO and alerting policies
  terraform/monitoring/03_service_slo.tf
  terraform/monitoring/04_alerting_policies.tf
  tests/monitoring_integration_test.py
Labels: cla: yes, lang: python, lang: yaml, priority: p2, type: feature request
