Repository GoogleCloudPlatform/cloud-ops-sandbox, pull requests merged in 2020-10, with the labels that each got.

#481 feat: node runtime12 and updated nodejs debugger
  .gitignore
  Makefile
  src/currencyservice/package-lock.json
  src/currencyservice/package.json
  src/currencyservice/server.js
  src/paymentservice/Dockerfile
  src/paymentservice/index.js
  src/paymentservice/package-lock.json
  src/paymentservice/package.json
  src/recommendationservice/recommendation_server.py
  terraform/03_gke_cluster.tf
Labels: cla: yes, dependencies, lang: javascript, priority: p2, type: cleanup

#485 loadgen: Step Load Pattern + command line tool
  .github/workflows/e2e-latest.yml
  .github/workflows/push-master.yml
  .github/workflows/push-tags.yml
  Makefile
  kubernetes-manifests/loadgenerator/locust-main-controller.yaml
  kubernetes-manifests/loadgenerator/locust-main-service.yaml
  kubernetes-manifests/loadgenerator/locust-worker-controller.yaml
  loadgenerator-manifests/loadgenerator.yaml
  skaffold.yaml
  src/loadgenerator/Dockerfile
  src/loadgenerator/locust-tasks/basic_locustfile.py
  src/loadgenerator/locust-tasks/requirements.in
  src/loadgenerator/locust-tasks/requirements.txt
  src/loadgenerator/locust-tasks/step_locustfile.py
  src/loadgenerator/requirements.in
  src/loadgenerator/requirements.txt
  src/loadgenerator/run.sh
  sre-recipes/sandboxctl
  terraform/03_gke_cluster.tf
  terraform/install.sh
  terraform/loadgen/00_loadgen.tf
  tests/provisioning/loadgen_test.py
Labels: cla: yes, lang: yaml, priority: p2, type: feature request

#488 Highlight Googler message
  terraform/install.sh
Labels: cla: yes, lang: shell

#333 Created Walkthrough Tutorial to open in Cloud Shell
  .github/workflows/e2e_scripts/run_install.sh
  README.md
  cloud-shell/Dockerfile
  cloud-shell/cloudshell_open_cp.sh
  docs/README.md
  docs/tutorial.md
  terraform/install.sh
  website/README.md
  website/index.html
Labels: cla: yes, lang: markdown, priority: p2, type: feature request

#493 Add member to CODEOWNERS
  CODEOWNERS
Labels: cla: yes

#487 Use sandboxctl for terraform scripts
  README.md
  cloud-shell/Dockerfile
  cloud-shell/cloudshell_open_cp.sh
  docs/README.md
  docs/tutorial.md
  sre-recipes/sandboxctl
  terraform/destroy.sh
  terraform/install.sh
Labels: cla: yes, lang: markdown, priority: p2, type: process

#489 Feat: customize how labeler bot detects languages with user config file
  .github/config.yml
Labels: cla: yes, priority: p2, type: feature request

#492 Fix: istio/gke version conflict by unpinning gke version
  Makefile
  terraform/03_gke_cluster.tf
Labels: cla: yes, priority: p2, type: bug

#497 Fix sandboxctl create
  sre-recipes/sandboxctl
Labels: cla: yes

#498 Fix release script and readme
  README.md
  make-release.sh
Labels: cla: yes, lang: shell

#506 Fix locust
  loadgenerator-manifests/loadgenerator.yaml
  src/loadgenerator/locust-tasks/basic_locustfile.py
  sre-recipes/sandboxctl
  terraform/install.sh
  terraform/loadgen/00_loadgen.tf
  tests/provisioning/loadgen_test.py
Labels: cla: yes, lang: yaml, priority: p2, type: bug

#510 ci: run e2e on prs to master & set renovate reviewer to nicole
  .github/workflows/e2e-latest.yml
  renovate.json
Labels: cla: yes, lang: yaml

#515 Switch out labeler bot for the version deployed on Yoshi infra
  .github/auto-label.yaml
Labels: cla: yes, lang: yaml

#514 Disable recipe1
  sre-recipes/recipe.py
  sre-recipes/recipes/encoding_recipe/encoding_recipe.py
  sre-recipes/sandboxctl
Labels: cla: yes, lang: python

#513 build: remove zones a and c temporarily as they are behind latest gke release
  terraform/03_gke_cluster.tf
Labels: cla: yes, lang: manifest, priority: p2

#512 Loadgen swarm tests
  tests/provisioning/loadgen_test.py
  tests/provisioning/requirements.txt
  tests/requirements.txt
Labels: cla: yes, lang: python

#516 Release/v0.4.0
  README.md
  cloud-shell/Dockerfile
  make-release.sh
  website/index.html
Labels: cla: yes

#518 ci: moved project_IDs from secrets to env variable
  .github/workflows/README.md
  .github/workflows/e2e-latest.yml
  .github/workflows/e2e-release.yml
  .github/workflows/push-master.yml
  .github/workflows/push-tags.yml
Labels: cla: yes, lang: yaml, priority: p2, type: process

#528 Use link to "#opencensus-to-become-opentelemetry" section
  docs/README.md
Labels: cla: yes, lang: markdown, priority: p2, type: docs

#526 Update auto-label.yaml
  .github/auto-label.yaml
Labels: cla: yes, lang: yaml

#527 Fix markdown formatting
  docs/README.md
Labels: cla: yes, lang: markdown, priority: p2, type: docs

#531 chore: Ignore invalid package versions RenovateBot tries to update
  renovate.json
Labels: automerge, cla: yes, type: process

#551 Updating Locust settings and screenshot for issue #503
  docs/README.md
  docs/images/user-guide/3-locust.png
  docs/tutorial.md
Labels: cla: yes, lang: markdown
