Repository GoogleCloudPlatform/cloud-ops-sandbox, pull requests merged in 2020-12, with the labels that each got.

#578 Extend rating service API with GET ratings/ call to simplify integration with frontend
  src/ratingservice/README.md
  src/ratingservice/main.py
  tests/ratingservice/main_test.py
Labels: cla: yes, lang: python

#581 integrate frontend service with rating service
  .github/workflows/ci.yml
  src/frontend/handlers.go
  src/frontend/main.go
  src/frontend/rest.go
  src/frontend/templates/home.html
  src/frontend/templates/product.html
Labels: cla: yes, lang: go

#562 Instructions in tutorial and guide for re-launching custom Cloud Shell
  docs/README.md
  docs/tutorial.md
Labels: cla: yes, lang: markdown

#586 add rating service monitoring metrics
  .github/workflows/ci.yml
  .gitignore
  src/frontend/rest.go
  terraform/monitoring/02_dashboards.tf
  terraform/monitoring/04_slos.tf
  terraform/monitoring/dashboards/ratingservice_dashboard.json
  tests/monitoring_integration_test.py
Labels: cla: yes, lang: manifest

#582 Fixing branding in release doc
  RELEASING.md
Labels: cla: yes, lang: markdown, type: bug

#584 feat: make loadgenerator optional
  sre-recipes/sandboxctl
  terraform/05_loadgen.tf
  terraform/install.sh
  terraform/variables.tf
Labels: cla: yes, lang: shell

#591 Fix recommendation service dependencies
  Makefile
  src/recommendationservice/requirements.in
  src/recommendationservice/requirements.txt
Labels: cla: yes, lang: python

#588 GRPC_HEALTH_PROBE_VERSION=v0.3.5
  src/adservice/Dockerfile
  src/cartservice/Dockerfile
  src/checkoutservice/Dockerfile
  src/currencyservice/Dockerfile
  src/emailservice/Dockerfile
  src/paymentservice/Dockerfile
  src/productcatalogservice/Dockerfile
  src/recommendationservice/Dockerfile
  src/shippingservice/Dockerfile
Labels: cla: yes, lang: go

#592 make recollect API follow the custom method guidelines
  src/ratingservice/main.py
  terraform/ratingservice/README.md
  terraform/ratingservice/main.tf
  tests/ratingservice/main_test.py
Labels: cla: yes, lang: manifest, lang: python

#597 ci: istio 1.8 requires installation confirmation
  terraform/istio/install_istio.sh
Labels: cla: yes, lang: shell

#608 add default value for emailservice env var
  src/emailservice/email_server.py
Labels: automerge, cla: yes, lang: python

#609 feat: run loadgen for a few seconds during installation
  terraform/install.sh
Labels: cla: yes, lang: shell, priority: p1, type: feature request

#610 make number of populated votes = 1
  terraform/ratingservice/configure_rating_db.sh
Labels: cla: yes, lang: shell

#611 Release/v0.5.0
  README.md
  cloud-shell/Dockerfile
  website/index.html
Labels: cla: yes, lang: markdown

#613 update README and other docs to include rating service
  CONTRIBUTING.md
  README.md
  docs/img/app-engine.png
  docs/img/architecture-diagram.png
  docs/img/hipster-shop-frontend-1.png
  docs/img/kubernetes.png
Labels: cla: yes, lang: markdown, type: docs
