Repository GoogleCloudPlatform/cloud-ops-sandbox, pull requests merged in 2020-09, with the labels that each got.

#411 Add website alert popup
  docs/index.html
Labels: cla: yes, lang: shell, priority: p2, type: feature request

#430 Monitoring readme
  docs/images/monitoring/dashboards-list.png
  docs/images/monitoring/log-based-metric.png
  docs/images/monitoring/sample-dashboard.png
  docs/images/monitoring/services-list.png
  docs/images/monitoring/slo-details.png
  docs/images/monitoring/uptime-check.png
  terraform/monitoring/README.md
Labels: cla: yes, priority: p3, type: process

#426 Release/v0.2.6
  README.md
  docs/index.html
Labels: cla: yes

#434 Update readme.md for tracing
  README.md
Labels: cla: yes, lang: markdown, priority: p2, type: docs

#439 [loadgen] Remove southamerica-east-1 from regions, replace with us-west-1 regions
  terraform/loadgen/00_loadgen.tf
Labels: cla: yes, type: bug

#421 Add telemetry to Terraform scripts
  cloud-shell/Dockerfile
  make-release.sh
  terraform/destroy.sh
  terraform/install.sh
  terraform/telemetry.py
Labels: cla: yes, lang: python, lang: shell, priority: p2, type: process

#423 Frontend latency SRE Recipe
  src/frontend/handlers.go
Labels: cla: yes, lang: go, priority: p3, type: feature request

#422 added CLI for sre recipes
  sre-recipes/README.md
  sre-recipes/__init__.py
  sre-recipes/recipe.py
  sre-recipes/recipes/currencies_recipe/__init__.py
  sre-recipes/recipes/currencies_recipe/currencies_recipe.py
  sre-recipes/requirements.txt
  sre-recipes/sandboxctl
Labels: cla: yes, priority: p2, type: process

#447 auth cluster for CLI & added to PATH
  cloud-shell/Dockerfile
  sre-recipes/recipes/currencies_recipe/currencies_recipe.py
Labels: automerge, cla: yes, priority: p1, type: bug

#442 Moved website to new directory for App Engine deployment
  docs/index.html
  website/cloudbuild.yaml
  website/css/main.css
  website/images/bg_01.png
  website/images/bg_02.png
  website/images/cloud-logo.svg
  website/images/cloud-shell.svg
  website/images/cloud.svg
  website/images/content_copy.svg
  website/images/done.svg
  website/images/github.svg
  website/images/google-cloud-logotype.svg
  website/images/hex_bg.svg
  website/images/logo_stackdriver.svg
  website/index.html
Labels: cla: yes, priority: p2, type: process

#446 Fix reattaching to existing projects
  .github/workflows/e2e-latest.yml
  .github/workflows/e2e-release.yml
  .github/workflows/e2e_scripts/clean.sh
  terraform/install.sh
  terraform/loadgen/00_loadgen.tf
  tests/provisioning/loadgen_test.py
Labels: cla: yes, priority: p2, type: bug

#450 Add workspace link line break
  terraform/install.sh
Labels: cla: yes

#420 Add RatingService to the demo app
  src/productcatalogservice/server.go
  src/ratingservice/.gcloudignore
  src/ratingservice/README.md
  src/ratingservice/main.py
  src/ratingservice/requirements.txt
  terraform/serverless/04_cloudsql.tf
  terraform/serverless/05_app_engine.tf
  terraform/serverless/info.tf
  terraform/serverless/install_serverless.sh
  tests/ratingservice/main_test.py
Labels: cla: yes, lang: python, priority: p2, type: feature request

#454 Release/v0.3.0
  README.md
  cloud-shell/Dockerfile
Labels: cla: yes, lang: markdown, priority: p2, type: process

#456 Fix website deployment
  make-release.sh
  website/README.md
  website/index.html
Labels: cla: yes, lang: markdown, type: docs

#457 remove probes from recommendation service
  kubernetes-manifests/recommendationservice.yaml
Labels: cla: yes, priority: p2, type: bug

#463 Fix destroy script
  terraform/destroy.sh
Labels: cla: yes, priority: p2, type: feature request

#448 Set up Workload Identity for GKE
  .github/workflows/e2e_scripts/clean.sh
  kubernetes-manifests/emailservice.yaml
  kubernetes-manifests/recommendationservice.yaml
  terraform/03_gke_cluster.tf
Labels: cla: yes, lang: yaml, priority: p2, type: bug

#461 Add Sandboxctl to path
  cloud-shell/Dockerfile
  cloud-shell/cloudshell_open_cp.sh
Labels: cla: yes, priority: p2, type: feature request

#460 Fix e2e provisioning tests
  .github/workflows/e2e-release.yml
  tests/provisioning/loadgen_test.py
  tests/provisioning/provision_test.py
  tests/provisioning/test_runner.py
Labels: cla: yes, priority: p2, type: process

#466 Log based metric fix
  terraform/monitoring/06_log_based_metric.tf
Labels: cla: yes, priority: p3, type: process

#468 Patch #448: Better solves MDS/GoogleAuth/Istio race condition
  kubernetes-manifests/emailservice.yaml
  kubernetes-manifests/recommendationservice.yaml
  terraform/03_gke_cluster.tf
  terraform/istio/install_istio.sh
  terraform/istio/istio_operator.yaml
Labels: cla: yes, lang: yaml, priority: p2

#472 User uncertified images
  README.md
  cloud-shell/README.md
  cloud-shell/cloudbuild.yaml
  make-release.sh
  website/index.html
Labels: cla: yes

#469 CLI refactor and hint method for sre recipes
  sre-recipes/README.md
  sre-recipes/recipe.py
  sre-recipes/recipes/currencies_recipe/currencies_recipe.py
  sre-recipes/sandboxctl
Labels: cla: yes, priority: p3, type: process

#475 E2e Fix: Use default GCE service account for Workload Identity
  .github/workflows/e2e_scripts/clean.sh
  terraform/03_gke_cluster.tf
Labels: cla: yes, lang: yaml

#484 Enable e2e latest on PRs with review requests & renovate bot configurations
  .github/workflows/e2e-latest.yml
  renovate.json
Labels: cla: yes, priority: p2, type: process

#486 Use certified image again
  .github/workflows/update-custom-image.yml
  cloud-shell/cloudbuild.yaml
  make-release.sh
  website/index.html
Labels: cla: yes, lang: yaml
