Repository GoogleCloudPlatform/cloud-ops-sandbox, pull requests merged in 2021-07, with the labels that each got.

#783 changing typo KBE to GKE
  terraform/install.sh
Labels: cla: yes, lang: shell, priority: p2, type: cleanup

#784 fix restoring existing projects
  docs/images/user-guide/64-cost-est.png
  docs/images/user-guide/65-cost-est2.png
  terraform/02_project.tf
  terraform/03_gke_cluster.tf
  terraform/loadgen/00_loadgen.tf
  tests/provisioning/loadgen_test.py
  tests/provisioning/provision_test.py
  website/content/en/docs/User Guide/Cost Explained/_index.md
  website/content/en/docs/images/user-guide/64-cost-est.png
  website/content/en/docs/images/user-guide/65-cost-est2.png
Labels: cla: yes, lang: manifest

#767 Release/v0.7.0
  README.md
  cloud-shell/Dockerfile
  make-release.sh
  website/deploy/index.html
  website/layouts/index.html
Labels: cla: yes, lang: markdown

#785 ci: add manually stage website action
  .github/workflows/README.md
  .github/workflows/manual-website-stage.yml
  .github/workflows/pr-comment-bot.yml
Labels: cla: yes, kokoro:force-run, lang: yaml

#799 chore: workflow changes
  .github/workflows/README.md
  .github/workflows/ci.yml
  .github/workflows/e2e-latest.yml
  .github/workflows/e2e-release.yml
  .github/workflows/push-containers.yaml
  .github/workflows/push-tags.yml
  .github/workflows/update-custom-image.yml
  .github/workflows/update-website.yml
  CONTRIBUTING.md
  RELEASING.md
  docs/README.md
  docs/tutorial.md
  make-release.sh
  terraform/ratingservice/README.md
Labels: cla: yes, lang: markdown

#803 ci: add new gitflow enforcer actions
  .github/workflows/README.md
  .github/workflows/check-tags.yml
  .github/workflows/gitflow-enforcer.yml
Labels: cla: yes, kokoro:force-run, lang: yaml

#786 ci: added e2e-upgrade workflow
  .github/workflows/README.md
  .github/workflows/e2e-upgrade.yml
Labels: cla: yes, lang: yaml

#805 ci: replaced release script with action
  .github/workflows/make-release.yml
  RELEASING.md
  cloud-shell/cloudbuild.yaml
  make-release.sh
Labels: cla: yes, lang: yaml

#806 ci: fix cloud build container workflow
  .github/workflows/update-custom-image.yml
  cloud-shell/Dockerfile
  cloud-shell/cloudbuild.yaml
Labels: cla: yes, lang: yaml

#769 fix: auto scaling min_node_count to align with spec
  terraform/03_gke_cluster.tf
Labels: cla: yes, lang: manifest

#807 fix: update outdated loadgen env variable in sandboxctl
  sre-recipes/sandboxctl
Labels: cla: yes

#821 fix(describe): Remove unnecessary " from output
  sre-recipes/sandboxctl
Labels: cla: yes, kokoro:force-run, lang: yaml

#810 fix: Increase frontend pod resources
  kubernetes-manifests/frontend.yaml
Labels: cla: yes, kokoro:force-run, lang: yaml
