Repository GoogleCloudPlatform/cloud-ops-sandbox, pull requests merged in 2021-06, with the labels that each got.

#729 Add cost and errors reporting doc in user guide
  docs/images/user-guide/51-Error-Reporting-podfailed.png
  docs/images/user-guide/52-Error-Reporting-pod.png
  docs/images/user-guide/53-Error-Reporting-logs.png
  docs/images/user-guide/54-Error-Reporting2.png
  docs/images/user-guide/55-Error-Reporting-failed-con-logs.png
  docs/images/user-guide/56-Error-Reporting-loadgen.png
  docs/images/user-guide/57-billing-menu.png
  docs/images/user-guide/58-billing-console.png
  docs/images/user-guide/59-resources-console.png
  docs/images/user-guide/60-gke-billing.png
  docs/images/user-guide/61-AppEngine-billing.png
  docs/images/user-guide/62-cloudsql-billing.png
  docs/images/user-guide/63-storage-metrics.png
  docs/images/user-guide/64-cost-est.png
  docs/images/user-guide/65-cost-est2.png
  docs/images/user-guide/66-AppEngine-billing-ui.png
  docs/images/user-guide/67-cloudsql-calc-menu.png
  docs/tutorial.md
  website/content/en/docs/User Guide/Cost Explained/_index.md
  website/content/en/docs/User Guide/Explore your project in GCP/_index.md
  website/content/en/docs/User Guide/Learn Cloud Operations/cloud_error_reporting.md
  website/content/en/docs/images/user-guide/51-Error-Reporting-podfailed.png
  website/content/en/docs/images/user-guide/52-Error-Reporting-pod.png
  website/content/en/docs/images/user-guide/53-Error-Reporting-logs.png
  website/content/en/docs/images/user-guide/54-Error-Reporting2.png
  website/content/en/docs/images/user-guide/55-Error-Reporting-failed-con-logs.png
  website/content/en/docs/images/user-guide/56-Error-Reporting-loadgen.png
  website/content/en/docs/images/user-guide/57-billing-menu.png
  website/content/en/docs/images/user-guide/58-billing-console.png
  website/content/en/docs/images/user-guide/59-resources-console.png
  website/content/en/docs/images/user-guide/60-gke-billing.png
  website/content/en/docs/images/user-guide/61-AppEngine-billing.png
  website/content/en/docs/images/user-guide/62-cloudsql-billing.png
  website/content/en/docs/images/user-guide/63-storage-metrics.png
  website/content/en/docs/images/user-guide/64-cost-est.png
  website/content/en/docs/images/user-guide/65-cost-est2.png
  website/content/en/docs/images/user-guide/66-AppEngine-billing-ui.png
  website/content/en/docs/images/user-guide/67-cloudsql-calc-menu.png
Labels: cla: yes, lang: markdown

#719 Refactor LoadGen to use Library Mode, and add SRE Recipe LoadGen API placeholder
  .github/workflows/e2e-latest.yml
  loadgenerator-manifests/loadgenerator.yaml
  src/loadgenerator/Dockerfile
  src/loadgenerator/app.py
  src/loadgenerator/init.py
  src/loadgenerator/locust_tasks/__init__.py
  src/loadgenerator/locust_tasks/basic_locustfile.py
  src/loadgenerator/locust_tasks/step_locustfile.py
  src/loadgenerator/logger.py
  src/loadgenerator/requirements.in
  src/loadgenerator/requirements.txt
  src/loadgenerator/run.sh
  src/loadgenerator/sre_recipe_utils.py
  tests/provisioning/loadgen_test.py
Labels: cla: yes, lang: python, priority: p2, python, type: feature request

#731 chore: update auto-label.yaml
  .github/auto-label.yaml
Labels: cla: yes, kokoro:force-run, kokoro:run, lang: yaml

#736 nit: Fix the target version to launch in getting started doc
  website/content/en/docs/getting_started.md
Labels: cla: yes, lang: markdown, type: docs

#737 nit: Lint and fix sandboxctl to meet Python3 standard
  sre-recipes/sandboxctl
Labels: cla: yes, lang: python, python

#735 Fix shellscript lines in Makefile
  Makefile
  kubernetes-manifests/frontend.yaml
Labels: api: container, cla: yes, lang: shell, lang: yaml

#732 Implement LoadGen SRE Recipe API
  loadgenerator-manifests/loadgenerator.yaml
  src/loadgenerator/README.md
  src/loadgenerator/app.py
  src/loadgenerator/locust_tasks/__init__.py
  src/loadgenerator/locust_tasks/sre_recipe_load_tasks.py
  src/loadgenerator/sre_recipe_utils.py
  tests/provisioning/loadgen_test.py
Labels: cla: yes, lang: python, type: feature request

#746 Trigger synthetic load from recipe0 - high latency
  src/loadgenerator/locust_tasks/__init__.py
  src/loadgenerator/locust_tasks/sre_recipe_load_tasks.py
  src/loadgenerator/sre_recipe_utils.py
  sre-recipes/README.md
  sre-recipes/recipes/currencies_recipe/currencies_recipe.py
  sre-recipes/requirements.txt
Labels: cla: yes, lang: python

#744 Add OpenTelemetry trace functionality to cartservice
  kubernetes-manifests/cartservice.yaml
  kubernetes-manifests/opentelemetrycollector.yaml
  skaffold.yaml
  src/cartservice/Startup.cs
  src/cartservice/cartservice.csproj
  src/cartservice/docker-compose.yaml
  terraform/03_gke_cluster.tf
Labels: cla: yes, lang: yaml

#743 Fix sandboxctl destroy timeout
  sre-recipes/recipe.py
  sre-recipes/sandboxctl
  terraform/destroy.sh
Labels: cla: yes, lang: python, lang: shell, python

#752 Add Redis Trace instrumentation to cartservice
  src/cartservice/Startup.cs
  src/cartservice/cartservice.csproj
  src/cartservice/cartstore/RedisCartStore.cs
Labels: cla: yes, lang: dotnet, type: feature request

#751 Add documentation to cartservice README.md
  docs/img/cartservice-opentelemetry-diagram.png
  src/cartservice/README.md
Labels: cla: yes, lang: dotnet

#764 Fix loadgen machine type
  terraform/loadgen/00_loadgen.tf
  tests/provisioning/loadgen_test.py
Labels: cla: yes, lang: manifest

#759 update terraform to v1.0.0
  cloud-shell/Dockerfile
  terraform/install.sh
Labels: cla: yes

#758 Open in Cloud Shell button bot
  .github/workflows/README.md
  .github/workflows/pr-comment-bot.yml
  CONTRIBUTING.md
Labels: cla: yes, lang: markdown

#762 remove sandboxctl "skip-workspace-prompt" argument
  .github/workflows/e2e-latest.yml
  .github/workflows/e2e-release.yml
  .github/workflows/e2e_scripts/run_install.sh
  sre-recipes/sandboxctl
  terraform/install.sh
Labels: cla: yes, lang: shell

#766 feat: Add Google Feedback to Sandbox main page
  CONTRIBUTING.md
  website/deploy/index.html
  website/layouts/index.html
Labels: cla: yes, lang: javascript, type: feature request
