Repository GoogleCloudPlatform/cloud-ops-sandbox, pull requests merged in 2021-05, with the labels that each got.

#689 Update 04_slos.tf
  terraform/monitoring/04_slos.tf
Labels: cla: yes, lang: manifest

#698 Issue #540
  website/content/en/docs/User Guide/Explore your project in GCP/_index.md
Labels: automerge, cla: yes, lang: markdown

#700 fix: add gcp debugger to email service
  src/emailservice/email_server.py
  src/emailservice/requirements.in
  src/emailservice/requirements.txt
  src/recommendationservice/recommendation_server.py
Labels: cla: yes, lang: python

#696 Readmes alignment
  website/content/en/docs/User Guide/Destroying your cluster/_index.md
  website/content/en/docs/User Guide/Explore your project in GCP/_index.md
  website/content/en/docs/getting_started.md
Labels: cla: yes, lang: markdown

#702 Update tutorial to include Opencensus metrics #542
  docs/images/user-guide/48-metrics-explorer-rpc.png
  docs/images/user-guide/49-metrics-explorer-filter-rpc.png
  docs/images/user-guide/50-cust-expr-dashboard.png
  website/content/en/docs/User Guide/Learn Ops Management/cloud_monitoring.md
Labels: cla: yes, lang: markdown

#701 Shorten Neo Guide and align missing content with Readme
  docs/README.md
  docs/tutorial.md
  website/content/en/docs/User Guide/Explore your project in GCP/_index.md
  website/content/en/docs/User Guide/Learn Ops Management/_index.md
  website/content/en/docs/User Guide/Learn Ops Management/cloud_error_reporting.md
  website/content/en/docs/User Guide/Learn Ops Management/cloud_logging.md
  website/content/en/docs/User Guide/Learn Ops Management/cloud_monitoring.md
Labels: cla: yes, lang: markdown

#705 chore: update python rsa dep
  src/emailservice/requirements.txt
  src/recommendationservice/requirements.txt
Labels: cla: yes, lang: python

#686 Decreasing allocation sizes
  CONTRIBUTING.md
  Makefile
  terraform/03_gke_cluster.tf
  terraform/loadgen/00_loadgen.tf
  terraform/ratingservice/main.tf
  tests/provisioning/provision_test.py
Labels: cla: yes, kokoro:force-run, kokoro:run, lang: manifest

#713 Align Website User guide with Readme docs
  README.md
  docs/tutorial.md
  website/content/en/docs/User Guide/Learn Cloud Operations/_index.md
  website/content/en/docs/User Guide/Learn Cloud Operations/cloud_debugger.md
  website/content/en/docs/User Guide/Learn Cloud Operations/cloud_error_reporting.md
  website/content/en/docs/User Guide/Learn Cloud Operations/cloud_logging.md
  website/content/en/docs/User Guide/Learn Cloud Operations/cloud_monitoring.md
  website/content/en/docs/User Guide/Learn Cloud Operations/cloud_profiler.md
  website/content/en/docs/User Guide/Learn Cloud Operations/cloud_slo_monitoring.md
  website/content/en/docs/User Guide/Learn Cloud Operations/cloud_trace.md
  website/content/en/docs/images/user-guide/20-monitoring-dashboards-kubernetes.png
  website/deploy/docs/images/user-guide/20-monitoring-dashboards-kubernetes.png
Labels: cla: yes, lang: markdown, type: docs

#717 Change installation time message in tutorial.md (Neo)
  docs/tutorial.md
Labels: cla: yes, lang: markdown

#714 Migrate from dep to modules in shippingservice
  src/shippingservice/Dockerfile
  src/shippingservice/Gopkg.lock
  src/shippingservice/Gopkg.toml
  src/shippingservice/README.md
  src/shippingservice/genproto.sh
  src/shippingservice/go.mod
  src/shippingservice/go.sum
  src/shippingservice/main.go
  src/shippingservice/shippingservice_test.go
Labels: cla: yes, lang: go

#716 Migrate from dep to modules in productcatalogservice
  src/productcatalogservice/Dockerfile
  src/productcatalogservice/Gopkg.lock
  src/productcatalogservice/Gopkg.toml
  src/productcatalogservice/README.md
  src/productcatalogservice/go.mod
  src/productcatalogservice/go.sum
  src/productcatalogservice/server.go
  src/productcatalogservice/server_test.go
Labels: cla: yes, lang: go

#715 Migrate from dep to modules in checkoutservice
  src/checkoutservice/Dockerfile
  src/checkoutservice/Gopkg.lock
  src/checkoutservice/Gopkg.toml
  src/checkoutservice/README.md
  src/checkoutservice/genproto.sh
  src/checkoutservice/go.mod
  src/checkoutservice/go.sum
  src/checkoutservice/main.go
  src/checkoutservice/money/money.go
  src/checkoutservice/money/money_test.go
Labels: cla: yes, lang: go

#724 Update gRPC and protobuf in Go services
  pb/demo.proto
  pb/grpc/health/v1/health.proto
  src/checkoutservice/Dockerfile
  src/checkoutservice/genproto.sh
  src/checkoutservice/genproto/demo.pb.go
  src/checkoutservice/genproto/demo_grpc.pb.go
  src/checkoutservice/go.mod
  src/checkoutservice/go.sum
  src/checkoutservice/main.go
  src/checkoutservice/tools.go
  src/frontend/genproto.sh
  src/productcatalogservice/Dockerfile
  src/productcatalogservice/genproto.sh
  src/productcatalogservice/genproto/demo.pb.go
  src/productcatalogservice/genproto/demo_grpc.pb.go
  src/productcatalogservice/go.mod
  src/productcatalogservice/go.sum
  src/productcatalogservice/server.go
  src/productcatalogservice/tools.go
  src/shippingservice/Dockerfile
  src/shippingservice/genproto.sh
  src/shippingservice/genproto/demo.pb.go
  src/shippingservice/genproto/demo_grpc.pb.go
  src/shippingservice/go.mod
  src/shippingservice/go.sum
  src/shippingservice/tools.go
  tests/provisioning/loadgen_test.py
  tests/ratingservice/main_test.py
Labels: cla: yes, lang: go, priority: p2, type: process

#723 Update OpenTelemetry Trace libraries versions in services in Python
  src/emailservice/Dockerfile
  src/emailservice/email_client.py
  src/emailservice/email_server.py
  src/emailservice/logger.py
  src/emailservice/requirements.in
  src/emailservice/requirements.txt
  src/recommendationservice/Dockerfile
  src/recommendationservice/logger.py
  src/recommendationservice/recommendation_server.py
  src/recommendationservice/requirements.in
  src/recommendationservice/requirements.txt
Labels: api: cloudtrace, cla: yes, lang: python, priority: p2, python, type: process

#730 Remove msg about creating Workspace in Cloud Operations
  terraform/install.sh
Labels: cla: yes, lang: shell
