Repository GoogleCloudPlatform/cloud-ops-sandbox, pull requests merged in 2021-01, with the labels that each got.

#614 update images to include rating service
  docs/README.md
  docs/images/user-guide/1-architecture.png
  docs/img/architecture-diagram.png
Labels: cla: yes, lang: markdown

#612 update cartservice
  src/cartservice/.dockerignore
  src/cartservice/Dockerfile
  src/cartservice/Program.cs
  src/cartservice/Services/CartServiceController.cs
  src/cartservice/Startup.cs
  src/cartservice/cartservice.csproj
  src/cartservice/generate_protos.bat
  tests/cartservice/cartservice.tests.csproj
  tests/cartservice/cartservice.tests.csproj.user
Labels: cla: yes, lang: dotnet, priority: p2, type: feature request

#622 fix: istio version
  .github/workflows/e2e-release.yml
  terraform/istio/install_istio.sh
Labels: cla: yes, lang: shell

#630 fix: cloud build timeout issue
  .github/workflows/update-custom-image.yml
  cloud-shell/cloudbuild.yaml
Labels: cla: yes, lang: yaml

#631 fix: add config-level timeout
  cloud-shell/cloudbuild.yaml
Labels: cla: yes, lang: yaml

#633 fix: change cartservice base image
  src/cartservice/Dockerfile
Labels: cla: yes, lang: dotnet
