Repository GoogleCloudPlatform/cloud-ops-sandbox, pull requests merged in 2021-09, with the labels that each got.

#811 feat(terraform): add GKE location to TF apply
  terraform/00_state.tf
  terraform/03_gke_cluster.tf
  terraform/install.sh
  terraform/variables.tf
Labels: cla: yes, lang: shell

#826 feat: Add config-based SRE Recipe Implementation
  .gitignore
  sre-recipes/recipe.py
  sre-recipes/recipe_runner.py
  sre-recipes/recipes/configs_based/README.md
  sre-recipes/recipes/configs_based/disabled/README.md
  sre-recipes/recipes/configs_based/disabled/recipe1.yaml
  sre-recipes/recipes/configs_based/recipe0.yaml
  sre-recipes/recipes/configs_based/recipe2.yaml
  sre-recipes/recipes/configs_based/recipe3.yaml
  sre-recipes/recipes/currencies_recipe/currencies_recipe.py
  sre-recipes/recipes/encoding_recipe/__init__.py
  sre-recipes/recipes/encoding_recipe/encoding_recipe.py
  sre-recipes/recipes/impl_based/README.md
  sre-recipes/recipes/impl_based/__init__.py
  sre-recipes/recipes/impl_based/base.py
  sre-recipes/recipes/impl_based/disabled/README.md
  sre-recipes/recipes/impl_based/disabled/dummy_recipe.py
  sre-recipes/recipes/ratings_freshness_recipe/__init__.py
  sre-recipes/recipes/ratings_freshness_recipe/ratings_freshness_recipe.py
  sre-recipes/recipes/recommendation_crash_recipe/__init__.py
  sre-recipes/recipes/recommendation_crash_recipe/recommendation_crash_recipe.py
  sre-recipes/requirements.txt
  sre-recipes/sandboxctl
  sre-recipes/utils.py
Labels: cla: yes, lang: python

#788 feat: add app version to GKE cluster
  terraform/03_gke_cluster.tf
  terraform/install.sh
  terraform/variables.tf
Labels: cla: yes, lang: manifest

#820 fix(terraform): Update provider version constraints
  terraform/01_provider.tf
  terraform/monitoring/00_provider.tf
  terraform/ratingservice/main.tf
  terraform/ratingservice/provider.tf
Labels: type: feature request, priority: p2, cla: yes, lang: manifest

#818 fix: currencyservice errors
  src/currencyservice/package-lock.json
  src/currencyservice/package.json
  src/currencyservice/server.js
  tests/recipes/test_recommendation_crash_recipe.sh
Labels: cla: yes, lang: javascript

#836 tests: Add integration tests for validating SRE Recipe config schema
  .github/workflows/ci.yml
  sre-recipes/README.md
  sre-recipes/recipes/configs_based/README.md
  sre-recipes/recipes/configs_based/recipe2.yaml
  sre-recipes/recipes/configs_based/schema/README.md
  sre-recipes/recipes/configs_based/schema/defs/README.md
  sre-recipes/recipes/configs_based/schema/defs/action-config-list.schema.json
  sre-recipes/recipes/configs_based/schema/defs/loadgen-spawn.schema.json
  sre-recipes/recipes/configs_based/schema/defs/loadgen-stop.schema.json
  sre-recipes/recipes/configs_based/schema/defs/multiple-choice-quiz.schema.json
  sre-recipes/recipes/configs_based/schema/defs/run-shell-commands.schema.json
  sre-recipes/recipes/configs_based/schema/schema.json
  sre-recipes/requirements.txt
  tests/recipes/validate_recipe_configs.py
  tests/requirements.txt
Labels: cla: yes, lang: markdown
