Repository GoogleCloudPlatform/cloud-ops-sandbox, pull requests merged in 2021-04, with the labels that each got.

#668 Fixing small website bugs before release
  website/README.md
  website/config.toml
  website/content/en/docs/_index.md
  website/content/en/docs/getting_started.md
  website/deploy/404.html
  website/deploy/docs/_print/index.html
  website/deploy/docs/getting_started/index.html
  website/deploy/docs/index.html
  website/deploy/docs/service_overview/index.html
  website/deploy/docs/user-guide/_print/index.html
  website/deploy/docs/user-guide/destroying-your-cluster/_print/index.html
  website/deploy/docs/user-guide/destroying-your-cluster/index.html
  website/deploy/docs/user-guide/explore-your-project-in-gcp/_print/index.html
  website/deploy/docs/user-guide/explore-your-project-in-gcp/index.html
  website/deploy/docs/user-guide/index.html
  website/deploy/docs/user-guide/learn-ops-management/_print/index.html
  website/deploy/docs/user-guide/learn-ops-management/cloud_debugger/index.html
  website/deploy/docs/user-guide/learn-ops-management/cloud_error_reporting/index.html
  website/deploy/docs/user-guide/learn-ops-management/cloud_logging/index.html
  website/deploy/docs/user-guide/learn-ops-management/cloud_monitoring/index.html
  website/deploy/docs/user-guide/learn-ops-management/cloud_profiler/index.html
  website/deploy/docs/user-guide/learn-ops-management/cloud_trace/index.html
  website/deploy/docs/user-guide/learn-ops-management/index.html
  website/deploy/docs/user-guide/set-up/_print/index.html
  website/deploy/docs/user-guide/set-up/index.html
  website/deploy/index.html
  website/deploy/search/index.html
  website/deploy/sitemap.xml
  website/layouts/index.html
Labels: cla: yes, lang: markdown, priority: p2, type: bug

#670 Release/v0.6.0
  README.md
  cloud-shell/Dockerfile
  make-release.sh
  website/deploy/index.html
  website/layouts/index.html
Labels: cla: yes, lang: shell, priority: p1, type: process

#671 fix: update pyyaml dependency
  src/recommendationservice/requirements.txt
Labels: cla: yes, lang: python

#654 B 644
  docs/README.md
  docs/images/user-guide/20-monitoring-dashboards-kubernetes.png
  docs/images/user-guide/36-checkoutservice-overview.png
  docs/images/user-guide/37-services-overview.png
  docs/images/user-guide/38-rating-sli.png
  docs/images/user-guide/39-checkout-service.png
  docs/images/user-guide/40-slo-review.png
  docs/images/user-guide/41-checkoutservice-define-sli.png
  docs/images/user-guide/42-checkoutservice-sli.png
  docs/images/user-guide/43-set-slo.png
  docs/images/user-guide/44-set-slo-burn-alert.png
  docs/images/user-guide/45-burn-rate-final.png
  docs/images/user-guide/46-crete-slo-burn-alert.png
  docs/images/user-guide/47-choose-checkout-custom-service.png
  docs/tutorial.md
  terraform/monitoring/04_slos.tf
Labels: cla: yes, lang: markdown

#682 added lock maintainence to rennovate.json
  renovate.json
Labels: cla: yes

#683 chore(deps): update profiler and semistandard npm versions
  src/currencyservice/package-lock.json
  src/currencyservice/package.json
  src/paymentservice/package-lock.json
  src/paymentservice/package.json
Labels: cla: yes, lang: javascript, priority: p1, type: process
