Repository GoogleCloudPlatform/cloud-ops-sandbox, pull requests merged in 2022-06, with the labels that each got.

#934 fix: Enable staleness and pull request size bots on the repo
  .github/auto-label.yaml
Labels: lang: yaml

#933 feat: simplify service dashboards
  terraform/monitoring/03_services.tf
  terraform/monitoring/04_slos.tf
  terraform/monitoring/05_alerting_policies.tf
Labels: lang: manifest

#931 fix: Cloud Ops permission errors
  terraform/03_gke_cluster.tf
Labels: lang: manifest

#930 feat: upgrade Istio 1.7.1 to ASM
  .github/workflows/e2e-latest.yml
  .github/workflows/e2e-release.yml
  .github/workflows/e2e-upgrade.yml
  .github/workflows/e2e_scripts/clean.sh
  .github/workflows/e2e_scripts/cleanup_monitoring.py
  .github/workflows/e2e_scripts/requirements.txt
  CONTRIBUTING.md
  cloud-shell/Dockerfile
  sre-recipes/sandboxctl
  sre-recipes/utils.py
  terraform/01_provider.tf
  terraform/02_project.tf
  terraform/03_gke_cluster.tf
  terraform/04_ratingservice.tf
  terraform/get_terraform_vars.sh
  terraform/install.sh
  terraform/istio/install_asm.sh
  terraform/istio/install_istio.sh
  terraform/istio/istio_operator.yaml
  terraform/monitoring/04_slos.tf
  terraform/monitoring/05_alerting_policies.tf
  terraform/monitoring/istio_service_setup.py
  terraform/monitoring/variables.tf
  tests/monitoring_integration_test.py
  tests/provisioning/provision_test.py
  tests/provisioning/requirements.txt
  tests/recipes/test_recommendation_crash_recipe.sh
  tests/requirements.txt
Labels: lang: yaml

#940 fix: sre-recipes don't fail on warning logs
  sre-recipes/recipe_runner.py
Labels: lang: python

#941 fix: github actions fix container build on release
  .github/workflows/README.md
  .github/workflows/make-release.yml
  .github/workflows/push-tags.yml
  .github/workflows/update-custom-image.yml
  RELEASING.md
Labels: lang: yaml

#938 fix: update frontend dependencies
  src/frontend/Gopkg.lock
  src/frontend/Gopkg.toml
Labels: lang: go

#932 chore(tests): Add cloud ops data tests
  .github/workflows/e2e-latest.yml
  .github/workflows/e2e-release.yml
  .github/workflows/e2e-upgrade.yml
  .github/workflows/e2e_scripts/clean.sh
  RELEASING.md
  sre-recipes/sandboxctl
  terraform/monitoring/03_services.tf
  tests/monitoring_integration_test.py
  tests/run_tests.sh
Labels: lang: python

#945 fix: Enable the cloud-sql-proxy path to Cloud SQL for ratingservice
  terraform/ratingservice/01_project.tf
  terraform/ratingservice/04_appengine.tf
Labels: lang: manifest

#946 chore: test adjustments
  .github/workflows/make-release.yml
  .github/workflows/update-custom-image.yml
  tests/run_tests.sh
Labels: lang: shell
